<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCMEuCk3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCMEuCk3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCMEuCk3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCMEuCk3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCMEuCk3\App_KernelDevDebugContainer([
    'container.build_hash' => 'CMEuCk3',
    'container.build_id' => 'cc5cc4a4',
    'container.build_time' => 1584835045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCMEuCk3');
